
public enum ClaseLexica {
	IDEN, ENT, REAL, PAP, PCIERRE, IGUAL, EQUIVALENTE, PUNTOCOMA, PUNTO,
	MAYOR, MENOR, MAYIGUAL, MENIGUAL, MAS, AND, OR, NOT, MENOS, POR, DIV, SEPARADOR, DIFERENTE, NUM, BOOL, EOF
}
