
public enum ClaseLexica {
	IDEN, ENT, REAL, PAP, PCIERRE, IGUAL, EQUIVALENTE, PUNTOCOMA,
	MAYOR, MENOR, MAYORIGUAL, MENORIGUAL, MAS, AND, OR, NOT, MENOS, POR, DIV, SEPARADOR, DIFERENTE, NUM, BOOL, TRUE, FALSE, EOF
}
